title: "Víctor Loureiro Sancho"
email: v.loureiro11@gmail.com
timezone: CET
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/miniature.png'
author: Víctor
paginate: 30
disqus: 'demowebsite'
locale: en_uk
lang: en_uk
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
categories: Machine Learning, Software, Security
#ganalytics: UA-113961478-1

# Authors
authors:
  victor:
    name: Víctor Loureiro Sancho
    display_name: Víctor LS
    avatar: 'assets/images/victor.png'
    email: v.loureiro11@gmail.com
    web: https://victorloureiro.github.io/
    linkedin: https://www.linkedin.com/in/victorloureirosancho/
    github: https://github.com/VictorLoureiro
    description: "Telecom Engineer | Software Developer | ML Curious"

# Social
social:
  linkedin: https://www.linkedin.com/in/victorloureirosancho/
  github: https://github.com/VictorLoureiro

#Collections
collections:
  projects:
    output: true

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
